### ISSUE TITLE
Error when statically configuring a persistent web hook

### ISSUE THREAD

**Issue by cutz** [NextThought/nti.webhooks#19]
I'm attempting to statically configure a persistent web hook. I'm using this zcml chunk

```zcml
<configure
	 xmlns="http://namespaces.zope.org/zope"
    	 xmlns:webhooks="http://nextthought.com/ntp/webhooks">
   
   <include package="zope.app.appsetup" />
   <include package="zope.generations" file="subscriber.zcml" />

   <exclude package="nti.webhooks" file="permissions.zcml" />
   <include package="nti.webhooks" />
   <webhooks:persistentSubscription
	site_path="/dataserver2/++etc++hostsites/alpha.dev/++etc++site/"
	for="nti.coremetadata.interfaces.IUser"
	when="zope.lifecycleevent.interfaces.IObjectAddedEvent"
	to="https://localhost:9999/hooks/user/created" />
</configure>
```

Which results in the below stack trace?

```
Traceback (most recent call last):
  File "///nti.dataserver-buildout/eggs/gunicorn-19.9.0-py2.7.egg/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "///nti.dataserver-buildout/sources/nti.dataserver/src/nti/appserver/nti_gunicorn.py", line 325, in init_process
    super(GeventApplicationWorker, self).init_process()
  File "///nti.dataserver-buildout/eggs/gunicorn-19.9.0-py2.7.egg/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "///nti.dataserver-buildout/eggs/gunicorn-19.9.0-py2.7.egg/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "///nti.dataserver-buildout/eggs/gunicorn-19.9.0-py2.7.egg/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "///nti.dataserver-buildout/eggs/gunicorn-19.9.0-py2.7.egg/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "///nti.dataserver-buildout/sources/nti.dataserver/src/nti/appserver/nti_gunicorn.py", line 755, in load
    relative_to=self.relpath)
  File "///nti.dataserver-buildout/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "///nti.dataserver-buildout/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "///nti.dataserver-buildout/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "///nti.dataserver-buildout/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "///nti.dataserver-buildout/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "///nti.dataserver-buildout/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "///nti.dataserver-buildout/eggs/PasteDeploy-2.1.0-py2.7.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "///nti.dataserver-buildout/sources/nti.dataserver/src/nti/appserver/standalone.py", line 50, in configure_app
    **settings)
  File "///nti.dataserver-buildout/sources/nti.dataserver/src/nti/appserver/application.py", line 552, in createApplication
    server = _create_server(create_ds, process_args)
  File "///nti.dataserver-buildout/sources/nti.dataserver/src/nti/appserver/application.py", line 434, in _create_server
    server = ds_class(dataDir)
  File "///nti.dataserver-buildout/sources/nti.dataserver/src/nti/dataserver/_Dataserver.py", line 460, in __init__
    super(Dataserver, self).__init__(parentDir)
  File "///nti.dataserver-buildout/sources/nti.dataserver/src/nti/dataserver/_Dataserver.py", line 126, in __init__
    self._open_dbs()
  File "///nti.dataserver-buildout/sources/nti.dataserver/src/nti/dataserver/_Dataserver.py", line 151, in _open_dbs
    self.db = self._setup_dbs(self._parentDir, None, None)
  File "///nti.dataserver-buildout/sources/nti.dataserver/src/nti/dataserver/_Dataserver.py", line 179, in _setup_dbs
    db = self.conf.connect_databases()  # Handles notifications, component registry
  File "///nti.dataserver-buildout/sources/nti.dataserver/src/nti/dataserver/config.py", line 600, in connect_databases
    notify(DatabaseOpened(xdb))
  File "///nti.dataserver-buildout/eggs/zope.event-4.4-py2.7.egg/zope/event/__init__.py", line 32, in notify
    subscriber(event)
  File "///nti.dataserver-buildout/eggs/zope.component-4.6.2-py2.7.egg/zope/component/event.py", line 27, in dispatch
    component_subscribers(event, None)
  File "///nti.dataserver-buildout/eggs/zope.component-4.6.2-py2.7.egg/zope/component/_api.py", line 134, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "//VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/zope/interface/registry.py", line 448, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "//VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/zope/interface/adapter.py", line 619, in subscribers
    subscription(*objects)
  File "///nti.dataserver-buildout/eggs/zope.app.appsetup-4.2.0-py2.7.egg/zope/app/appsetup/bootstrap.py", line 168, in bootStrapSubscriber
    zope.event.notify(zope.processlifetime.DatabaseOpenedWithRoot(db))
  File "///nti.dataserver-buildout/eggs/zope.event-4.4-py2.7.egg/zope/event/__init__.py", line 32, in notify
    subscriber(event)
  File "///nti.dataserver-buildout/eggs/zope.component-4.6.2-py2.7.egg/zope/component/event.py", line 27, in dispatch
    component_subscribers(event, None)
  File "///nti.dataserver-buildout/eggs/zope.component-4.6.2-py2.7.egg/zope/component/_api.py", line 134, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "//VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/zope/interface/registry.py", line 448, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "//VirtualEnvs/nti.dataserver-buildout/lib/python2.7/site-packages/zope/interface/adapter.py", line 619, in subscribers
    subscription(*objects)
  File "///nti.dataserver-buildout/eggs/zope.generations-5.0.0-py2.7.egg/zope/generations/generations.py", line 528, in evolveMinimumSubscriber
    evolve(event.database, EVOLVEMINIMUM)
  File "///nti.dataserver-buildout/eggs/zope.generations-5.0.0-py2.7.egg/zope/generations/generations.py", line 442, in evolve
    if generation == manager.generation:
  File "///nti.dataserver-buildout/eggs/nti.webhooks-0.0.3-py2.7.egg/nti/webhooks/generations.py", line 256, in generation
    return self._finalized_state.generation
AttributeError: 'NoneType' object has no attribute 'generation'
```

Based on the _Important_ block in the [documentation](https://ntiwebhooks.readthedocs.io/en/latest/static-persistent.html#adding-a-subscription) I'm wondering if I have something misconfigured given the larger context this slug is being used in. Ideas?

**Comment by jamadden** [comment]
I don't think you need or want to include `zope.app.appsetup`. Your code is manually notifying both `DatabaseOpened` and `DatabaseOpenedWithRoot`. The former is what sets up `_finalized_state`, while the latter is what runs the generation. By including `zope.app.appsetup`, you're getting into a situation where `zope.app.appsetup` listens for `DatabaseOpened` and (recursively) fires `DatabaseOpenedWithRoot` *while there are subscribers for `DatabaseOpened` still pending*.

(I also think your configuration already includes `zope.generations` so you don't need it here.)

**Comment by cutz** [comment]
Thanks that got me further.
